# Generated by Django 5.2.7 on 2025-10-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('resource_type', models.PositiveSmallIntegerField(choices=[(1, 'Video'), (2, 'Course'), (3, 'Article')])),
                ('platform', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Started'), (2, 'In Progress'), (3, 'Completed')], default=1)),
                ('hours_spent', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('difficulty_rating', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
